# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baxtergui.ui'
#
# Created: Mon Jun  8 18:17:09 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BaxterGUI(object):
    def setupUi(self, BaxterGUI):
        BaxterGUI.setObjectName("BaxterGUI")
        BaxterGUI.resize(881, 630)
        self.centralWidget = QtGui.QWidget(BaxterGUI)
        self.centralWidget.setObjectName("centralWidget")
        self.tab_checks = QtGui.QTabWidget(self.centralWidget)
        self.tab_checks.setGeometry(QtCore.QRect(40, 50, 771, 481))
        self.tab_checks.setObjectName("tab_checks")
        self.tab_1_general = QtGui.QWidget()
        self.tab_1_general.setObjectName("tab_1_general")
        self.listWidget_2 = QtGui.QListWidget(self.tab_1_general)
        self.listWidget_2.setGeometry(QtCore.QRect(240, 91, 181, 311))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtGui.QLabel(self.tab_1_general)
        self.label.setGeometry(QtCore.QRect(240, 50, 71, 21))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tab_1_general)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(40, 50, 160, 351))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3)
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.pushButton_4 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_9 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.tab_checks.addTab(self.tab_1_general, "")
        self.tab_2_buttons = QtGui.QWidget()
        self.tab_2_buttons.setObjectName("tab_2_buttons")
        self.tbl_buttons = QtGui.QTableWidget(self.tab_2_buttons)
        self.tbl_buttons.setGeometry(QtCore.QRect(20, 20, 421, 401))
        self.tbl_buttons.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbl_buttons.setDragDropOverwriteMode(False)
        self.tbl_buttons.setRowCount(12)
        self.tbl_buttons.setColumnCount(4)
        self.tbl_buttons.setObjectName("tbl_buttons")
        self.tbl_buttons.setColumnCount(4)
        self.tbl_buttons.setRowCount(12)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(3, item)
        self.tbl_buttons.horizontalHeader().setVisible(False)
        self.tbl_buttons.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_buttons.horizontalHeader().setHighlightSections(False)
        self.tbl_buttons.verticalHeader().setVisible(False)
        self.list_buttons = QtGui.QListWidget(self.tab_2_buttons)
        self.list_buttons.setGeometry(QtCore.QRect(580, 60, 171, 351))
        self.list_buttons.setObjectName("list_buttons")
        self.label_4 = QtGui.QLabel(self.tab_2_buttons)
        self.label_4.setGeometry(QtCore.QRect(590, 30, 111, 17))
        self.label_4.setObjectName("label_4")
        self.tab_checks.addTab(self.tab_2_buttons, "")
        self.tab_3_infrared = QtGui.QWidget()
        self.tab_3_infrared.setObjectName("tab_3_infrared")
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tab_3_infrared)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(29, 30, 601, 341))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.left_ir_range = QtGui.QProgressBar(self.verticalLayoutWidget_7)
        self.left_ir_range.setProperty("value", 24)
        self.left_ir_range.setObjectName("left_ir_range")
        self.verticalLayout_5.addWidget(self.left_ir_range)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.right_ir_range = QtGui.QProgressBar(self.verticalLayoutWidget_7)
        self.right_ir_range.setMaximum(100)
        self.right_ir_range.setProperty("value", 40)
        self.right_ir_range.setTextVisible(True)
        self.right_ir_range.setFormat("%pcm")
        self.right_ir_range.setObjectName("right_ir_range")
        self.verticalLayout_5.addWidget(self.right_ir_range)
        self.btn_test_distances = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.btn_test_distances.setObjectName("btn_test_distances")
        self.verticalLayout_5.addWidget(self.btn_test_distances)
        self.btn_stop_ir_distance = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.btn_stop_ir_distance.setObjectName("btn_stop_ir_distance")
        self.verticalLayout_5.addWidget(self.btn_stop_ir_distance)
        self.tab_checks.addTab(self.tab_3_infrared, "")
        self.tab_4_sonar = QtGui.QWidget()
        self.tab_4_sonar.setObjectName("tab_4_sonar")
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_4_sonar)
        self.tableWidget_2.setGeometry(QtCore.QRect(40, 130, 256, 192))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_7 = QtGui.QLabel(self.tab_4_sonar)
        self.label_7.setGeometry(QtCore.QRect(50, 90, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab_4_sonar)
        self.label_8.setGeometry(QtCore.QRect(190, 90, 67, 17))
        self.label_8.setObjectName("label_8")
        self.pushButton_12 = QtGui.QPushButton(self.tab_4_sonar)
        self.pushButton_12.setGeometry(QtCore.QRect(380, 360, 99, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtGui.QPushButton(self.tab_4_sonar)
        self.pushButton_13.setGeometry(QtCore.QRect(220, 350, 141, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.tab_checks.addTab(self.tab_4_sonar, "")
        self.tab_5_camera = QtGui.QWidget()
        self.tab_5_camera.setObjectName("tab_5_camera")
        self.camera_image = QtGui.QWidget(self.tab_5_camera)
        self.camera_image.setGeometry(QtCore.QRect(59, 99, 480, 300))
        self.camera_image.setObjectName("camera_image")
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_5_camera)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(570, 100, 160, 301))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_left_camera = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.cb_left_camera.setCheckable(True)
        self.cb_left_camera.setChecked(False)
        self.cb_left_camera.setObjectName("cb_left_camera")
        self.verticalLayout_6.addWidget(self.cb_left_camera)
        self.cb_head_camera = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.cb_head_camera.setObjectName("cb_head_camera")
        self.verticalLayout_6.addWidget(self.cb_head_camera)
        self.cb_right_camera = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.cb_right_camera.setObjectName("cb_right_camera")
        self.verticalLayout_6.addWidget(self.cb_right_camera)
        self.btn_test_all_cameras = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.btn_test_all_cameras.setObjectName("btn_test_all_cameras")
        self.verticalLayout_6.addWidget(self.btn_test_all_cameras)
        self.btn_save_image = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.btn_save_image.setObjectName("btn_save_image")
        self.verticalLayout_6.addWidget(self.btn_save_image)
        self.tab_checks.addTab(self.tab_5_camera, "")
        self.tab_6_arms = QtGui.QWidget()
        self.tab_6_arms.setObjectName("tab_6_arms")
        self.pushButton_16 = QtGui.QPushButton(self.tab_6_arms)
        self.pushButton_16.setGeometry(QtCore.QRect(80, 60, 261, 71))
        self.pushButton_16.setObjectName("pushButton_16")
        self.tab_checks.addTab(self.tab_6_arms, "")
        self.tab_7_head = QtGui.QWidget()
        self.tab_7_head.setObjectName("tab_7_head")
        self.pushButton_17 = QtGui.QPushButton(self.tab_7_head)
        self.pushButton_17.setGeometry(QtCore.QRect(70, 60, 251, 71))
        self.pushButton_17.setObjectName("pushButton_17")
        self.tab_checks.addTab(self.tab_7_head, "")
        self.tab_8_display = QtGui.QWidget()
        self.tab_8_display.setObjectName("tab_8_display")
        self.label_9 = QtGui.QLabel(self.tab_8_display)
        self.label_9.setGeometry(QtCore.QRect(70, 50, 91, 21))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_8_display)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 50, 160, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_5 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.radioButton_4 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_6 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout.addWidget(self.radioButton_8)
        self.pushButton_18 = QtGui.QPushButton(self.tab_8_display)
        self.pushButton_18.setGeometry(QtCore.QRect(490, 80, 181, 51))
        self.pushButton_18.setObjectName("pushButton_18")
        self.tab_checks.addTab(self.tab_8_display, "")
        self.tab_9_led = QtGui.QWidget()
        self.tab_9_led.setObjectName("tab_9_led")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_9_led)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 110, 160, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.label_10 = QtGui.QLabel(self.tab_9_led)
        self.label_10.setGeometry(QtCore.QRect(50, 70, 151, 17))
        self.label_10.setObjectName("label_10")
        self.pushButton_19 = QtGui.QPushButton(self.tab_9_led)
        self.pushButton_19.setGeometry(QtCore.QRect(430, 280, 99, 27))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_11 = QtGui.QLabel(self.tab_9_led)
        self.label_11.setGeometry(QtCore.QRect(230, 70, 151, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.tab_9_led)
        self.label_12.setGeometry(QtCore.QRect(440, 70, 151, 17))
        self.label_12.setObjectName("label_12")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_9_led)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(230, 110, 160, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_3.addWidget(self.checkBox_8)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tab_9_led)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(420, 110, 160, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_11 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_4.addWidget(self.checkBox_11)
        self.checkBox_9 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_4.addWidget(self.checkBox_9)
        self.checkBox_10 = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_4.addWidget(self.checkBox_10)
        self.pushButton_20 = QtGui.QPushButton(self.tab_9_led)
        self.pushButton_20.setGeometry(QtCore.QRect(420, 330, 201, 27))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtGui.QPushButton(self.tab_9_led)
        self.pushButton_21.setGeometry(QtCore.QRect(420, 370, 99, 27))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtGui.QPushButton(self.tab_9_led)
        self.pushButton_22.setGeometry(QtCore.QRect(530, 370, 99, 27))
        self.pushButton_22.setObjectName("pushButton_22")
        self.tab_checks.addTab(self.tab_9_led, "")
        self.tab_10_gripper = QtGui.QWidget()
        self.tab_10_gripper.setObjectName("tab_10_gripper")
        self.pushButton_23 = QtGui.QPushButton(self.tab_10_gripper)
        self.pushButton_23.setGeometry(QtCore.QRect(90, 60, 99, 27))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtGui.QPushButton(self.tab_10_gripper)
        self.pushButton_24.setGeometry(QtCore.QRect(300, 60, 99, 27))
        self.pushButton_24.setObjectName("pushButton_24")
        self.tab_checks.addTab(self.tab_10_gripper, "")
        BaxterGUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(BaxterGUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 881, 25))
        self.menuBar.setObjectName("menuBar")
        BaxterGUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(BaxterGUI)
        self.mainToolBar.setObjectName("mainToolBar")
        BaxterGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(BaxterGUI)
        self.statusBar.setObjectName("statusBar")
        BaxterGUI.setStatusBar(self.statusBar)

        self.retranslateUi(BaxterGUI)
        self.tab_checks.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(BaxterGUI)

    def retranslateUi(self, BaxterGUI):
        BaxterGUI.setWindowTitle(QtGui.QApplication.translate("BaxterGUI", "BaxterGUI", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BaxterGUI", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("BaxterGUI", "Disable robot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("BaxterGUI", "Create report", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("BaxterGUI", "Enable robot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("BaxterGUI", "Send report by mail", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("BaxterGUI", "Open log directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("BaxterGUI", "Run tests", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("BaxterGUI", "Skip Test", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_1_general), QtGui.QApplication.translate("BaxterGUI", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("BaxterGUI", "Left Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("BaxterGUI", "States", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("BaxterGUI", "Right Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("BaxterGUI", "States", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BaxterGUI", "Buttons to push", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_2_buttons), QtGui.QApplication.translate("BaxterGUI", "Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BaxterGUI", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.left_ir_range.setFormat(QtGui.QApplication.translate("BaxterGUI", "%pcm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BaxterGUI", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_test_distances.setText(QtGui.QApplication.translate("BaxterGUI", "Test distances", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop_ir_distance.setText(QtGui.QApplication.translate("BaxterGUI", "Stop test", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_3_infrared), QtGui.QApplication.translate("BaxterGUI", "Infrared", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BaxterGUI", "Sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("BaxterGUI", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("BaxterGUI", "Stop test", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("BaxterGUI", "Test distances", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_4_sonar), QtGui.QApplication.translate("BaxterGUI", "Sonar", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_left_camera.setText(QtGui.QApplication.translate("BaxterGUI", "Left camera", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_head_camera.setText(QtGui.QApplication.translate("BaxterGUI", "Head camera", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_right_camera.setText(QtGui.QApplication.translate("BaxterGUI", "Right camera", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_test_all_cameras.setText(QtGui.QApplication.translate("BaxterGUI", "Test all cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_image.setText(QtGui.QApplication.translate("BaxterGUI", "Save image", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_5_camera), QtGui.QApplication.translate("BaxterGUI", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("BaxterGUI", "Move arms through entire space", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_6_arms), QtGui.QApplication.translate("BaxterGUI", "Arms", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("BaxterGUI", "Move head", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_7_head), QtGui.QApplication.translate("BaxterGUI", "Head", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BaxterGUI", "Show screen", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("BaxterGUI", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("BaxterGUI", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("BaxterGUI", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("BaxterGUI", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("BaxterGUI", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("BaxterGUI", "Show all for 10 seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_8_display), QtGui.QApplication.translate("BaxterGUI", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BaxterGUI", "Enable navigator  LED", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("BaxterGUI", "Blink all LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("BaxterGUI", "Enable sonar LED", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("BaxterGUI", "Set halo LED", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("BaxterGUI", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("BaxterGUI", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("BaxterGUI", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("BaxterGUI", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("BaxterGUI", "Test all LEDs consecutively", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("BaxterGUI", "Blinking", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("BaxterGUI", "Not blinking", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_9_led), QtGui.QApplication.translate("BaxterGUI", "LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("BaxterGUI", "Test left gripper", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("BaxterGUI", "Test right gripper", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_10_gripper), QtGui.QApplication.translate("BaxterGUI", "Gripper", None, QtGui.QApplication.UnicodeUTF8))

