# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/baxter_gui/baxtergui.ui'
#
# Created: Fri Jul 10 15:48:47 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BaxterGUI(object):
    def setupUi(self, BaxterGUI):
        BaxterGUI.setObjectName("BaxterGUI")
        BaxterGUI.resize(881, 630)
        self.centralWidget = QtGui.QWidget(BaxterGUI)
        self.centralWidget.setObjectName("centralWidget")
        self.tab_checks = QtGui.QTabWidget(self.centralWidget)
        self.tab_checks.setGeometry(QtCore.QRect(40, 40, 771, 481))
        self.tab_checks.setObjectName("tab_checks")
        self.tab_1_general = QtGui.QWidget()
        self.tab_1_general.setObjectName("tab_1_general")
        self.listWidget_2 = QtGui.QListWidget(self.tab_1_general)
        self.listWidget_2.setGeometry(QtCore.QRect(240, 91, 181, 311))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtGui.QLabel(self.tab_1_general)
        self.label.setGeometry(QtCore.QRect(240, 50, 71, 21))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tab_1_general)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(40, 50, 160, 351))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_disable = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.btn_disable.setObjectName("btn_disable")
        self.verticalLayout_7.addWidget(self.btn_disable)
        self.btn_enable = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.btn_enable.setEnabled(False)
        self.btn_enable.setObjectName("btn_enable")
        self.verticalLayout_7.addWidget(self.btn_enable)
        self.btn_tuck = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.btn_tuck.setObjectName("btn_tuck")
        self.verticalLayout_7.addWidget(self.btn_tuck)
        self.btn_untuck = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.btn_untuck.setObjectName("btn_untuck")
        self.verticalLayout_7.addWidget(self.btn_untuck)
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.btn_open_log_dir = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.btn_open_log_dir.setObjectName("btn_open_log_dir")
        self.verticalLayout_7.addWidget(self.btn_open_log_dir)
        self.pushButton_6 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_9 = QtGui.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.tab_checks.addTab(self.tab_1_general, "")
        self.tab_6_arms = QtGui.QWidget()
        self.tab_6_arms.setObjectName("tab_6_arms")
        self.btn_arms_test = QtGui.QPushButton(self.tab_6_arms)
        self.btn_arms_test.setGeometry(QtCore.QRect(80, 60, 261, 71))
        self.btn_arms_test.setObjectName("btn_arms_test")
        self.tab_checks.addTab(self.tab_6_arms, "")
        self.tab_2_buttons = QtGui.QWidget()
        self.tab_2_buttons.setObjectName("tab_2_buttons")
        self.tbl_buttons = QtGui.QTableWidget(self.tab_2_buttons)
        self.tbl_buttons.setGeometry(QtCore.QRect(20, 20, 421, 401))
        self.tbl_buttons.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbl_buttons.setDragDropOverwriteMode(False)
        self.tbl_buttons.setRowCount(12)
        self.tbl_buttons.setColumnCount(4)
        self.tbl_buttons.setObjectName("tbl_buttons")
        self.tbl_buttons.setColumnCount(4)
        self.tbl_buttons.setRowCount(12)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_buttons.setHorizontalHeaderItem(3, item)
        self.tbl_buttons.horizontalHeader().setVisible(False)
        self.tbl_buttons.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_buttons.horizontalHeader().setHighlightSections(False)
        self.tbl_buttons.verticalHeader().setVisible(False)
        self.list_buttons = QtGui.QListWidget(self.tab_2_buttons)
        self.list_buttons.setGeometry(QtCore.QRect(580, 60, 171, 351))
        self.list_buttons.setObjectName("list_buttons")
        self.label_4 = QtGui.QLabel(self.tab_2_buttons)
        self.label_4.setGeometry(QtCore.QRect(590, 30, 111, 17))
        self.label_4.setObjectName("label_4")
        self.tab_checks.addTab(self.tab_2_buttons, "")
        self.tab_3_infrared = QtGui.QWidget()
        self.tab_3_infrared.setObjectName("tab_3_infrared")
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tab_3_infrared)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(29, 30, 724, 251))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setLineWidth(1)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.left_ir_range = QtGui.QProgressBar(self.verticalLayoutWidget_7)
        self.left_ir_range.setMaximum(40)
        self.left_ir_range.setProperty("value", 24)
        self.left_ir_range.setObjectName("left_ir_range")
        self.verticalLayout_5.addWidget(self.left_ir_range)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.right_ir_range = QtGui.QProgressBar(self.verticalLayoutWidget_7)
        self.right_ir_range.setMaximum(40)
        self.right_ir_range.setProperty("value", 40)
        self.right_ir_range.setTextVisible(True)
        self.right_ir_range.setFormat("%vcm")
        self.right_ir_range.setObjectName("right_ir_range")
        self.verticalLayout_5.addWidget(self.right_ir_range)
        self.tab_checks.addTab(self.tab_3_infrared, "")
        self.tab_4_sonar = QtGui.QWidget()
        self.tab_4_sonar.setObjectName("tab_4_sonar")
        self.tbl_sonar = QtGui.QTableWidget(self.tab_4_sonar)
        self.tbl_sonar.setGeometry(QtCore.QRect(40, 30, 361, 401))
        self.tbl_sonar.setRowCount(12)
        self.tbl_sonar.setColumnCount(2)
        self.tbl_sonar.setObjectName("tbl_sonar")
        self.tbl_sonar.setColumnCount(2)
        self.tbl_sonar.setRowCount(12)
        item = QtGui.QTableWidgetItem()
        self.tbl_sonar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_sonar.setHorizontalHeaderItem(1, item)
        self.tbl_sonar.verticalHeader().setVisible(False)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_4_sonar)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(510, 110, 160, 128))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_sonar_reset = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sonar_reset.setEnabled(True)
        self.btn_sonar_reset.setObjectName("btn_sonar_reset")
        self.verticalLayout_8.addWidget(self.btn_sonar_reset)
        self.btn_sonar_enable = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sonar_enable.setObjectName("btn_sonar_enable")
        self.verticalLayout_8.addWidget(self.btn_sonar_enable)
        self.btn_sonar_disable = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_sonar_disable.setObjectName("btn_sonar_disable")
        self.verticalLayout_8.addWidget(self.btn_sonar_disable)
        self.tab_checks.addTab(self.tab_4_sonar, "")
        self.tab_5_camera = QtGui.QWidget()
        self.tab_5_camera.setObjectName("tab_5_camera")
        self.camera_image = QtGui.QWidget(self.tab_5_camera)
        self.camera_image.setGeometry(QtCore.QRect(59, 99, 480, 300))
        self.camera_image.setObjectName("camera_image")
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_5_camera)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(570, 100, 160, 301))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_left_camera = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.cb_left_camera.setCheckable(True)
        self.cb_left_camera.setChecked(False)
        self.cb_left_camera.setObjectName("cb_left_camera")
        self.verticalLayout_6.addWidget(self.cb_left_camera)
        self.cb_head_camera = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.cb_head_camera.setObjectName("cb_head_camera")
        self.verticalLayout_6.addWidget(self.cb_head_camera)
        self.cb_right_camera = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.cb_right_camera.setObjectName("cb_right_camera")
        self.verticalLayout_6.addWidget(self.cb_right_camera)
        self.btn_test_all_cameras = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.btn_test_all_cameras.setObjectName("btn_test_all_cameras")
        self.verticalLayout_6.addWidget(self.btn_test_all_cameras)
        self.btn_save_image = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.btn_save_image.setObjectName("btn_save_image")
        self.verticalLayout_6.addWidget(self.btn_save_image)
        self.label_7 = QtGui.QLabel(self.tab_5_camera)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 671, 61))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.tab_checks.addTab(self.tab_5_camera, "")
        self.tab_7_head = QtGui.QWidget()
        self.tab_7_head.setObjectName("tab_7_head")
        self.btn_head_test = QtGui.QPushButton(self.tab_7_head)
        self.btn_head_test.setGeometry(QtCore.QRect(70, 60, 251, 71))
        self.btn_head_test.setObjectName("btn_head_test")
        self.tab_checks.addTab(self.tab_7_head, "")
        self.tab_8_display = QtGui.QWidget()
        self.tab_8_display.setObjectName("tab_8_display")
        self.label_9 = QtGui.QLabel(self.tab_8_display)
        self.label_9.setGeometry(QtCore.QRect(70, 50, 91, 21))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_8_display)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 50, 160, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_display_white = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.cb_display_white.setObjectName("cb_display_white")
        self.verticalLayout.addWidget(self.cb_display_white)
        self.cb_display_black = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.cb_display_black.setObjectName("cb_display_black")
        self.verticalLayout.addWidget(self.cb_display_black)
        self.cb_display_red = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.cb_display_red.setObjectName("cb_display_red")
        self.verticalLayout.addWidget(self.cb_display_red)
        self.cb_display_green = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.cb_display_green.setObjectName("cb_display_green")
        self.verticalLayout.addWidget(self.cb_display_green)
        self.cb_display_blue = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.cb_display_blue.setObjectName("cb_display_blue")
        self.verticalLayout.addWidget(self.cb_display_blue)
        self.btn_display_show_all = QtGui.QPushButton(self.tab_8_display)
        self.btn_display_show_all.setGeometry(QtCore.QRect(490, 80, 181, 51))
        self.btn_display_show_all.setObjectName("btn_display_show_all")
        self.tab_checks.addTab(self.tab_8_display, "")
        self.tab_9_led = QtGui.QWidget()
        self.tab_9_led.setObjectName("tab_9_led")
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_9_led)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 30, 641, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.gridLayoutWidget = QtGui.QWidget(self.tab_9_led)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 70, 641, 224))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_left_itb_light_outer = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_left_itb_light_outer.setObjectName("cb_left_itb_light_outer")
        self.verticalLayout_3.addWidget(self.cb_left_itb_light_outer)
        self.cb_torso_left_itb_light_outer = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_torso_left_itb_light_outer.setObjectName("cb_torso_left_itb_light_outer")
        self.verticalLayout_3.addWidget(self.cb_torso_left_itb_light_outer)
        self.cb_right_itb_light_outer = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_right_itb_light_outer.setObjectName("cb_right_itb_light_outer")
        self.verticalLayout_3.addWidget(self.cb_right_itb_light_outer)
        self.cb_torso_right_itb_light_outer = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_torso_right_itb_light_outer.setObjectName("cb_torso_right_itb_light_outer")
        self.verticalLayout_3.addWidget(self.cb_torso_right_itb_light_outer)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cb_led_halo_red = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_led_halo_red.setObjectName("cb_led_halo_red")
        self.verticalLayout_4.addWidget(self.cb_led_halo_red)
        self.cb_led_halo_green = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_led_halo_green.setObjectName("cb_led_halo_green")
        self.verticalLayout_4.addWidget(self.cb_led_halo_green)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_left_itb_light_inner = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_left_itb_light_inner.setObjectName("cb_left_itb_light_inner")
        self.verticalLayout_2.addWidget(self.cb_left_itb_light_inner)
        self.cb_torso_left_itb_light_inner = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_torso_left_itb_light_inner.setObjectName("cb_torso_left_itb_light_inner")
        self.verticalLayout_2.addWidget(self.cb_torso_left_itb_light_inner)
        self.cb_right_itb_light_inner = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_right_itb_light_inner.setObjectName("cb_right_itb_light_inner")
        self.verticalLayout_2.addWidget(self.cb_right_itb_light_inner)
        self.cb_torso_right_itb_light_inner = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_torso_right_itb_light_inner.setObjectName("cb_torso_right_itb_light_inner")
        self.verticalLayout_2.addWidget(self.cb_torso_right_itb_light_inner)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_9_led)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(70, 300, 644, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_test_led = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_test_led.setEnabled(False)
        self.btn_test_led.setObjectName("btn_test_led")
        self.horizontalLayout_2.addWidget(self.btn_test_led)
        self.btn_led_stop = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_led_stop.setEnabled(False)
        self.btn_led_stop.setObjectName("btn_led_stop")
        self.horizontalLayout_2.addWidget(self.btn_led_stop)
        self.btn_blinking = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_blinking.setEnabled(False)
        self.btn_blinking.setObjectName("btn_blinking")
        self.horizontalLayout_2.addWidget(self.btn_blinking)
        self.btn_not_blinking = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_not_blinking.setEnabled(False)
        self.btn_not_blinking.setObjectName("btn_not_blinking")
        self.horizontalLayout_2.addWidget(self.btn_not_blinking)
        self.btn_blink_all = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_blink_all.setObjectName("btn_blink_all")
        self.horizontalLayout_2.addWidget(self.btn_blink_all)
        self.tab_checks.addTab(self.tab_9_led, "")
        self.tab_10_gripper = QtGui.QWidget()
        self.tab_10_gripper.setObjectName("tab_10_gripper")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_10_gripper)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 160, 273, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_gripper_left_test = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_left_test.setObjectName("btn_gripper_left_test")
        self.gridLayout_2.addWidget(self.btn_gripper_left_test, 4, 0, 1, 1)
        self.btn_gripper_left_close = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_left_close.setObjectName("btn_gripper_left_close")
        self.gridLayout_2.addWidget(self.btn_gripper_left_close, 3, 0, 1, 1)
        self.btn_gripper_left_calibrate = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_left_calibrate.setObjectName("btn_gripper_left_calibrate")
        self.gridLayout_2.addWidget(self.btn_gripper_left_calibrate, 1, 0, 1, 1)
        self.btn_gripper_right_test = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_right_test.setObjectName("btn_gripper_right_test")
        self.gridLayout_2.addWidget(self.btn_gripper_right_test, 4, 1, 1, 1)
        self.btn_gripper_left_open = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_left_open.setObjectName("btn_gripper_left_open")
        self.gridLayout_2.addWidget(self.btn_gripper_left_open, 2, 0, 1, 1)
        self.btn_gripper_right_calibrate = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_right_calibrate.setObjectName("btn_gripper_right_calibrate")
        self.gridLayout_2.addWidget(self.btn_gripper_right_calibrate, 1, 1, 1, 1)
        self.btn_gripper_right_close = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_right_close.setObjectName("btn_gripper_right_close")
        self.gridLayout_2.addWidget(self.btn_gripper_right_close, 3, 1, 1, 1)
        self.btn_gripper_right_open = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_gripper_right_open.setObjectName("btn_gripper_right_open")
        self.gridLayout_2.addWidget(self.btn_gripper_right_open, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.tab_checks.addTab(self.tab_10_gripper, "")
        BaxterGUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(BaxterGUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 881, 25))
        self.menuBar.setObjectName("menuBar")
        BaxterGUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(BaxterGUI)
        self.mainToolBar.setObjectName("mainToolBar")
        BaxterGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(BaxterGUI)
        self.statusBar.setObjectName("statusBar")
        BaxterGUI.setStatusBar(self.statusBar)

        self.retranslateUi(BaxterGUI)
        self.tab_checks.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BaxterGUI)

    def retranslateUi(self, BaxterGUI):
        BaxterGUI.setWindowTitle(QtGui.QApplication.translate("BaxterGUI", "BaxterGUI", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BaxterGUI", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_disable.setText(QtGui.QApplication.translate("BaxterGUI", "Disable robot", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_enable.setText(QtGui.QApplication.translate("BaxterGUI", "Enable robot", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_tuck.setText(QtGui.QApplication.translate("BaxterGUI", "Tuck arms", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_untuck.setText(QtGui.QApplication.translate("BaxterGUI", "Untuck arms", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("BaxterGUI", "Create report", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("BaxterGUI", "Send report by mail", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open_log_dir.setText(QtGui.QApplication.translate("BaxterGUI", "Open log directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("BaxterGUI", "Run tests", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("BaxterGUI", "Skip Test", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_1_general), QtGui.QApplication.translate("BaxterGUI", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arms_test.setText(QtGui.QApplication.translate("BaxterGUI", "Move arms through entire space", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_6_arms), QtGui.QApplication.translate("BaxterGUI", "Arms", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("BaxterGUI", "Left Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("BaxterGUI", "States", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("BaxterGUI", "Right Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_buttons.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("BaxterGUI", "States", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BaxterGUI", "Buttons to push", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_2_buttons), QtGui.QApplication.translate("BaxterGUI", "Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("BaxterGUI", "Shows the distance from the infrared distance sensors inside the wrist. Check, if the bars are moving when you move in front of the sensors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BaxterGUI", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.left_ir_range.setFormat(QtGui.QApplication.translate("BaxterGUI", "%vcm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BaxterGUI", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_3_infrared), QtGui.QApplication.translate("BaxterGUI", "Infrared", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_sonar.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("BaxterGUI", "Sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_sonar.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("BaxterGUI", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sonar_reset.setText(QtGui.QApplication.translate("BaxterGUI", "Reset distances", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sonar_enable.setText(QtGui.QApplication.translate("BaxterGUI", "Enable sonar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sonar_disable.setText(QtGui.QApplication.translate("BaxterGUI", "Disable sonar", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_4_sonar), QtGui.QApplication.translate("BaxterGUI", "Sonar", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_left_camera.setText(QtGui.QApplication.translate("BaxterGUI", "Left camera", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_head_camera.setText(QtGui.QApplication.translate("BaxterGUI", "Head camera", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_right_camera.setText(QtGui.QApplication.translate("BaxterGUI", "Right camera", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_test_all_cameras.setText(QtGui.QApplication.translate("BaxterGUI", "Test all cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_image.setText(QtGui.QApplication.translate("BaxterGUI", "Save image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BaxterGUI", "Choose a camera and wait patently. It takes while to switch them. Check if there are no artifacts inside the camera image.", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_5_camera), QtGui.QApplication.translate("BaxterGUI", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_head_test.setText(QtGui.QApplication.translate("BaxterGUI", "Move head", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_7_head), QtGui.QApplication.translate("BaxterGUI", "Head", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BaxterGUI", "Show screen", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_display_white.setText(QtGui.QApplication.translate("BaxterGUI", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_display_black.setText(QtGui.QApplication.translate("BaxterGUI", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_display_red.setText(QtGui.QApplication.translate("BaxterGUI", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_display_green.setText(QtGui.QApplication.translate("BaxterGUI", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_display_blue.setText(QtGui.QApplication.translate("BaxterGUI", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_display_show_all.setText(QtGui.QApplication.translate("BaxterGUI", "Show all for 10 seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_8_display), QtGui.QApplication.translate("BaxterGUI", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BaxterGUI", "Enable inner navigator  LED", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("BaxterGUI", "Enable outer navigator  LED", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("BaxterGUI", "Set halo LED", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_left_itb_light_outer.setText(QtGui.QApplication.translate("BaxterGUI", "Left arm", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_torso_left_itb_light_outer.setText(QtGui.QApplication.translate("BaxterGUI", "Left torso", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_right_itb_light_outer.setText(QtGui.QApplication.translate("BaxterGUI", "Right arm", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_torso_right_itb_light_outer.setText(QtGui.QApplication.translate("BaxterGUI", "Right torso", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_led_halo_red.setText(QtGui.QApplication.translate("BaxterGUI", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_led_halo_green.setText(QtGui.QApplication.translate("BaxterGUI", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_left_itb_light_inner.setText(QtGui.QApplication.translate("BaxterGUI", "Left arm", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_torso_left_itb_light_inner.setText(QtGui.QApplication.translate("BaxterGUI", "Left torso", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_right_itb_light_inner.setText(QtGui.QApplication.translate("BaxterGUI", "Right arm", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_torso_right_itb_light_inner.setText(QtGui.QApplication.translate("BaxterGUI", "Right torso", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_test_led.setText(QtGui.QApplication.translate("BaxterGUI", "Test all LEDs consecutively", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_led_stop.setText(QtGui.QApplication.translate("BaxterGUI", "Stop test", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_blinking.setText(QtGui.QApplication.translate("BaxterGUI", "Blinking", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_not_blinking.setText(QtGui.QApplication.translate("BaxterGUI", "Not blinking", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_blink_all.setText(QtGui.QApplication.translate("BaxterGUI", "Blink/Stop all LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_9_led), QtGui.QApplication.translate("BaxterGUI", "LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_left_test.setText(QtGui.QApplication.translate("BaxterGUI", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_left_close.setText(QtGui.QApplication.translate("BaxterGUI", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_left_calibrate.setText(QtGui.QApplication.translate("BaxterGUI", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_right_test.setText(QtGui.QApplication.translate("BaxterGUI", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_left_open.setText(QtGui.QApplication.translate("BaxterGUI", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_right_calibrate.setText(QtGui.QApplication.translate("BaxterGUI", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_right_close.setText(QtGui.QApplication.translate("BaxterGUI", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gripper_right_open.setText(QtGui.QApplication.translate("BaxterGUI", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BaxterGUI", "Left Gripper", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BaxterGUI", "Right Gripper", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_checks.setTabText(self.tab_checks.indexOf(self.tab_10_gripper), QtGui.QApplication.translate("BaxterGUI", "Gripper", None, QtGui.QApplication.UnicodeUTF8))

